version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 3003:27017
    volumes:
      - mongodb_data_container:/data/db
  mysql_container:
    build:
      dockerfile: Mysql/DockerfileMysql
      context: .
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: huydv
      MYSQL_USER: huydv
      MYSQL_PASSWORD: a123456
    hostname: mysql_container
    volumes:
      - .././mysql:/var/lib/mysql
      - ./Mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3308:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=elasticsearch-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
       - .././dataEs01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  mongodb_data_container: