version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 3003:27017
    volumes:
      - mongodb_data_container:/data/db
  mysql_container:
    build:
      dockerfile: Mysql/DockerfileMysql
      context: .
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: huydv
      MYSQL_USER: huydv
      MYSQL_PASSWORD: a123456
    hostname: mysql_container
    volumes:
      - .././mysql:/var/lib/mysql
      - ./Mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3308:3306
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./../dataEs01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://localhost:9200
volumes:
  mongodb_data_container: